### ISSUE TITLE
New module: Subsampler (andersonbrito)

### ISSUE THREAD

**Issue by jsbrittain** [kraemer-lab/vneyard#2]
Pre-check:
- [X] I have searched the [`vneyard` repository](https://github.com/kraemer-lab/vneyard) and was not able to find a similar module that already exists.

Proposed module name [e.g. 'Download file']: Subsampler (andersonbrito)
Proposed category [e.g. 'Tutorial']: Subsamplers
Description of module: A pipeline for subsampling genomic data based on epidemiological time series data.

Is this module based on an existing software package [Y/N]: Y
If yes, please find a link to the package (preferably the github): 
[subsampler](https://github.com/andersonbrito/subsampler)

Describe any alternatives you've considered: N/A

Add any other context or screenshots about the feature request here: N/A

**Comment by joetsui1994** [comment]
Suggestion: Genome-subsampler (andersonbrito)?
