### ISSUE TITLE
Enhanced BEASTgen support

### ISSUE THREAD

**Issue by jsbrittain** [kraemer-lab/vneyard#20]
Enhance BEASTgen support.
Current BEASTgen module is here: https://github.com/kraemer-lab/vneyard/tree/main/workflows/Utility/modules/BEASTgen
Does this provide sufficient functionality? Two principal questions:
1) can enhancements be made to improve usability?
2) is a more general xml parser required to make the necessary substitutions?

With regards to point 1, the existing module docstring states:
```python
"""BEASTgen

A simple program for transforming data from one format to another [https://beast.community/beastgen]. For example, change a NEXUS file into a FASTA file.

This module calls "beastgen [arguments] <template> <input> <output>" where arguments is a string of command line arguments. This can include the option ‘-D’ which allows the user to specify additional variables and their values that are specific to a BEASTGen operation (see https://beast.community/beastgen for more information). The template file is a BEASTGen template file that specifies how the input file should be transformed. The input file is the file to be transformed. The output file is the file that will be created by the transformation. Note that emplate and input files must be concrete (not symbolic links) for BEASTGen to work.

Params:
    Template filename (str): BEASTGen template file [concrete]
    Input filename (str): Input file [concrete]
    Output filename (str): Output file
    Arguments (str): Command line arguments
        See https://beast.community/beastgen for available options
"""
```

In particular, the '-D' parameter is provided to the module as a string. We could adjust this so that users provide a list / dictionary of keys and values which are formatting into the '-D' parameter behind the scenes.

**Comment by joetsui1994** [comment]
> @joetsui1994 see above comment: _'In particular, the '-D' parameter is provided to the module as a string. We could adjust this so that users provide a list / dictionary of keys and values which are formatting into the '-D' parameter behind the scenes.'_
> 
> Do we think this would be a viable solution?

This works, but I think it might be a good idea to provide a little more guardrail (it's quite easy to make mistakes for someone like me). So for example of parsing the sequence dates, it would be nice to have all the options as selectable.

**Comment by jsbrittain** [comment]
Sure, we have begun specialising fields in the GRAPEVNE editor (see the file picker for example https://github.com/kraemer-lab/GRAPEVNE/pull/279); we can implement a [date picker](https://mui.com/x/react-date-pickers/) using the same approach.
